version: "3"
services:
  admin-client:
    build: ./admin-server
    ports:
      - 3000:3000
    volumes:
      - ./admin-server/src:/admin-app/src
      - ./admin-server/public:/admin-app/public
    links:
      - proxy-server
  proxy-server:
    build: ./proxy-server
    ports:
      - 8080:8080
    volumes:
      - ./proxy-server:/proxy-app
    links:
      - client-server
  client-server:
    build: ./client-server
    ports:
      - 80:80
    volumes:
      - ./client-server:/client-app
