version: "3"
services:
  admin-client:
    build: ./admin-server
    ports:
      - 3000:3000
    volumes:
      - ./admin-server/src:/admin-app/src
      - ./admin-server/public:/admin-app/public
    links:
      - proxy-server
  proxy-server:
    build: ./proxy-server
    ports:
      - 6001:6001
    volumes:
      - ./proxy-server:/proxy-app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
    links:
      - client-server
  client-server:
    build: ./client-server
    ports:
      - 5001:5001
    volumes:
      - ./client-server:/client-app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
